bytecodealliance/StarlingMonkey

CMakeLists.txt
builtins/web/console.cpp
include/extension-api.h
runtime/allocator.cpp
runtime/engine.cpp
runtime/script_loader.cpp

This is the bare minimum changes I need to get ComponentizeJS to work on top of StarlingMonkey.
* `cabi_realloc` as a weak symbol so it can be overridden to support the bulk deallocation strategy we use
* A new `script_value()` on the engine, allowing to get the value of the top-level script. For a script it would be the last statement value, and for a module it is defined to be the module namespace itself.
* Allowing the console `console_builtin_log` to be overridable as a weak symbol
* Supporting cycles in the script loader (since ComponentizeJS has a cycle with its bindings module)
* Removing the full path in the debug logs for script errors, showing only the base-path-relative filename
* Fixing relative resolution to be parent-relative always
* Adding support for `RelWithDebInfo` …

feat: minimum componentize changes

---

runtime/engine.cpp
runtime/js.cpp

These new weak symbols enable better runtime layering, and were needed to build against compute runtime.

Set more weak symbols for runtime layering

---

runtime/script_loader.cpp
tests/cases/smoke/smoke-dependency.js

Adds simple support for extension searching in imports.

Support extension searching

---

builtins/web/fetch/request-response.cpp
builtins/web/streams/native-stream-source.cpp
builtins/web/streams/transform-stream.cpp

I'm currently building a custom request and response version against StarlingMonkey streams, which isn't currently working due to this hard dependence. Having the streams builtins include from request and response seems inverted in terms of the desired layering.
This removes that dependence, fixing the build layering for this use case.

Native stream layering

---

runtime/script_loader.cpp

This fixes a bug where stacks contain the relative specifiers in errors like:
```
@./rel-path.js:17:32
app@index.js:69:25
@index.js:53:23
```
where instead it should be `dir/rel-path.js` in the stack.

Use resolved path in stacks

---

include/extension-api.h
runtime/engine.cpp
runtime/script_loader.cpp
runtime/script_loader.h

This adds support for defining builtin modules from JS objects, which are then lazily turned into synthetic modules when imported, based on enumerating the own keys of the object and making those the exports of the synthetic module.
Useful for supporting custom internal APIs without needing to define globals.

Support builtin modules

---

builtins/web/base64.cpp
tests/integration/btoa/btoa.js

Remove underscore from base64DecodeTable

---

README.md
builtins/web/fetch/fetch-api.cpp
builtins/web/fetch/fetch_event.cpp
builtins/web/fetch/request-response.cpp
builtins/web/timers.cpp
host-apis/wasi-0.2.0-rc-2023-10-18/host_api.cpp
host-apis/wasi-0.2.0-rc-2023-12-05/host_api.cpp
host-apis/wasi-0.2.0/host_api.cpp
include/extension-api.h
include/host_api.h
runtime/engine.cpp
runtime/event_loop.cpp
runtime/event_loop.h
tests/integration/assert.js
tests/integration/btoa/btoa.js
tests/integration/handlers.js
tests/integration/test-server.js
tests/integration/timers/timers.js
tests/tests.cmake

This PR reworks the event loop and adds integration tests for the timers builtins.
The `run_event_loop` function is extended to support `incr_event_loop_lifetime` and `decr_event_loop_lifetime` calls which determine how long the event loop lifetime should run for, and when this is zero only a single jobs processing is done.
This PR also updates the task class to support `poll` instead of `select` and makes `ready` a static method.
Resolves https://github.com/bytecodealliance/StarlingMonkey/issues/37, https://github.com/bytecodealliance/StarlingMonkey/issues/39.

Event loop reworking, timers tests

---

builtins/web/crypto/crypto-algorithm.cpp
tests/integration/assert.js
tests/integration/crypto/crypto.js
tests/integration/handlers.js
tests/tests.cmake

This updates the crypto implementation with the PR in https://github.com/fastly/js-compute-runtime/pull/667 that was missed in the current implementation.
It also ports and verifies the full test suite is passing.

fix: crypto support & tests

---

builtins/web/fetch/fetch_event.cpp
builtins/web/performance.cpp
tests/integration/handlers.js
tests/integration/performance/performance.js
tests/integration/tests/performance.js
tests/tests.cmake

Adds tests for the performance builtin and fixes its initialization on the fetch event start.

fix: performance builtin and tests

---

host-apis/wasi-0.2.0/host_api.cpp
include/host_api.h

I needed these changes to get the release build to work on https://github.com/bytecodealliance/StarlingMonkey/pull/52, but can confirm this works on js-compute-runtime and ComponentizeJS.

fix: release build on fetch rework

---

cmake/add_builtin.cmake
cmake/builtins.cmake
cmake/openssl.cmake
runtime/encode.h

This patch makes it possible for users of the `add_builtins()` CMake function to specify a per-builtin dependency on another target.  This has been used to fix #42.

Allow specifying dependencies from subprojects

---

builtins/web/timers.cpp
include/extension-api.h

Fastly's js-compute-runtime does not support timer subscriptions, and instead virtual timers are used which check their deadlines as part of the normal event loop operation.
This PR implements a concept of deadlines for all tasks, so that the host select implementation can use those deadlines to progress task deadlines for hosts without timing subscriptions.
Feedback very welcome. This is one of the last pieces needed for the migration to StarlingMonkey for js-compute-runtime, with the migration passing 99% of all other tests down to this feature.

feat: support task deadlines

---

builtins/web/base64.cpp
builtins/web/crypto/crypto.cpp
builtins/web/fetch/request-response.cpp
builtins/web/streams/compression-stream.cpp

Specifically, some of the `noGC` guards had issues that could lead to panics during exception throwing, and some of the loops over multiple buffers where overly complex.

Improve handling of GC managed array buffers

---

builtins/web/timers.cpp

Strictly speaking, `clearTimeout` and `clearInterval` are valid noops when passed invalid values, therefore there is no reason to ban them at initialization time.
This behaviour is for some reason needed for Fastly's web platform test suite as well.
It does no harm, so I see no reason not to land this provided that `setTimeout` and `setInterval` remain protected.

timers: allow clearTimeout and clearInterval during initialization

---

host-apis/wasi-0.2.0-rc-2023-10-18/host_api.cpp
host-apis/wasi-0.2.0-rc-2023-12-05/host_api.cpp
host-apis/wasi-0.2.0/host_api.cpp
include/extension-api.h
runtime/event_loop.cpp

Updates the `HostApi::select` interface to take a reference to a vector instead of a pointer.

refactor: select to take a tasks vector reference

---

builtins/web/timers.cpp
runtime/event_loop.cpp
tests/integration/test-server.js
tests/integration/timers/timers.js

Before this patch, timer (i.e., `setTimeout`/`setInterval`) returned the pollable handles as IDs. This is problematic, because pollable handles are reused, leading to content potentially clearing the wrong timer.
Additionally, the code wasn't robust against a timer being cleared in its own callback, leading to a failing assertion.
I also added a few tweaks to the test code that I did while writing the test for this.

Bugfixes for `setTimeout` and `setInterval`

---

builtins/web/timers.cpp
tests/integration/timers/timers.js

This fixes a bug where `clearTimeout(null)` could clear a valid timeout if one existed at timer id `0`, by starting the timer ids from `1`. Affected a real web platform test!

fix: zero coercion timeout removal bug

---

crates/rust-url/Cargo.lock
crates/rust-url/Cargo.toml

This updates to the latest `url` crate dependency, fixing a couple of web platform tests in the process (which were required to get Fastly's WPT to pass, along with https://github.com/bytecodealliance/StarlingMonkey/pull/69).

deps: use latest rust url

---

builtins/web/base64.cpp
builtins/web/fetch/fetch-errors.h
builtins/web/streams/stream-errors.h
builtins/web/text-codec/text-codec-errors.h

Adds the `builtin.h` include to the new error header files so if they are included directly there aren't ordering issues.

add builtin includes to error headers

---

builtins/web/base64.cpp
builtins/web/base64.h
builtins/web/crypto/crypto-algorithm.cpp

Adds back the ability to call `convertJSValueToByteString` for a `HandleValue` by declaring the header for the original function variant. Necessary for Fastly's `statusText` setter to pass the web platform tests, because converting to a string first was altering unsupported characters.

feat: allow direct base64 call against HandleValue

---

builtins/web/timers.cpp
include/extension-api.h
runtime/engine.cpp
runtime/event_loop.cpp
runtime/event_loop.h

This was necessary to get one of the WPT cases to pass for Fastly's implementation.
Our implementation of checking task deadlines for timer tasks uses a redundant singular invalid handle (`-2`) to indicate a timer handle for a non-existent subscription. If we gave every timer a unique handle we would be using up the real handle ID space.
But the `cancel_task` currently assumes handle uniqueness when finding the handle.
This supports non-unique handles for tasks by taking the task itself to `cancel_task` instead of its handle to look it up from, storing timers as a map from timer ids to task pointers.
I can confirm this is working correctly in the WPT test case for Fastly.

fix: support non-unique handles for timers

---

cmake/init-corrosion.cmake

We had a failed publish on Fastly due to a different toolchain being installed by default and not having the `wasm32-wasi` target loaded.
This adds an explicit `--toolchain` flag to the `rustup target add` command, which should avoid issues like that in future.

fix: wasm32-wasi install for toolchain

---

cmake/openssl.cmake

it looks like openssl broke their links when they launched their new website? https://www.openssl.org/source/openssl-3.0.7.tar.gz 404s and is now at https://openssl.org/source/old/3.0/openssl-3.0.7.tar.gz

Update openssl url to new location

---

builtins/web/fetch/headers.cpp
builtins/web/fetch/headers.h

This includes some simple refactoring including unused code paths and also adds some extra state assertions, including encoding the state transition invariant that we never transition from `Uninitialized` to `HostOnly`. If this invariant changes in future we can always relax it again, but it helped my understanding of the state machine to note these assertions.

fix: headers refactoring and state transition invariants

---

builtins/web/fetch/fetch-api.cpp
builtins/web/fetch/fetch_event.cpp
builtins/web/fetch/request-response.cpp
builtins/web/fetch/request-response.h
tests/e2e/stream-forwarding/expect_serve_body.txt
tests/e2e/stream-forwarding/stream-forwarding.js

This fixes a crashing bug in a trivial scenario: `event.respondWith(new Response(someUpstreamResponse.body, someUpstreamResponse);`
It's not entirely clear to me why WPT didn't catch this, though it's possible that the tests that would've done so abort early for trivial reasons, such as our missing `FormData` support.
Instead, I added an e2e test to cover this, which fails without this patch.
(There are small unrelated tweaks to the runtime-eval support which I applied in debugging the test.)

Fix bugs with streaming outgoing bodies

---

README.md
cmake/spidermonkey.cmake

When developing StarlingMonkey using an existing SpiderMonkey build with no SM changes, it is very convenient to download and use pre-built artifacts for SM from the CI on `spidermonkey-wasi-embedding`, and we do not want to lose this convenience or approachability.
However, when modifying SpiderMonkey itself, it is nearly impossible to do development with the current setup: the debug loop requires merging changes to `gecko-dev` with one PR, updating the hash in `spidermonkey-wasi-embedding` with another PR, getting both merged and waiting for the build in CI before StarlingMonkey can use the new engine.
Rather than require a local hack for such cases, this modifies the SpiderMonkey CMake module to recognize a `SPIDERMONKEY_BINARIES` environment variable, and use artifacts there instead. …

 SpiderMonkey CMake package: use alternate artifacts if specified.

---

CMakeLists.txt

In #89, I had added an alternative (under `USE_WASM_OPT=OFF`) to avoid expensive wasm-opt runs for local development. However I had replaced this with `wasm-tools strip`, which strips all custom sections, including those important for component-related linkage. Getting further along my integration path I discovered the world info for the module was missing.
This PR instead uses `wasm-opt -O0 --strip-debug`, which does what I want (using the same tool as the ordinary build path) without the expensive opt passes.

CMake build: do not strip component-related custom sections in non-wasm-opt config.

---

tests/wpt-harness/wpt.cmake

As identified by @cfallin this fixes the `WPT_ROOT` environment variable to be correctly referenced.

fix: providing a custom WPT_ROOT env var

---

.github/workflows/main.yml
builtins/web/streams/transform-stream.cpp

This adds a CI job for the debug build on WPT, and also fixes an assertion failure which looks like a bug in transform streams.
I've posted a separate issue for this bug in https://github.com/bytecodealliance/StarlingMonkey/issues/112 to be resolved separately.
Necessary for Fastly's WPT to pass for the debug build.

ci: add WPT debug build, fix streams assertion failure

---

cmake/weval.cmake

This includes the [Reducifier](https://github.com/cfallin/waffle/pull/13) in waffle (the compiler library underlying weval), which supports compiling irreducible control flow to Wasm. It should address any corner cases where weval'ing PBL with bytecode produces irreducible control flow.

Update to weval 0.2.11.

---

cmake/weval.cmake

This pulls in some follow-up fixes to the earlier 0.2.11 upgrade (#140): the irreducibility check is now precise rather than approximate, so it doesn't trigger unnecessarily, and part of the transform (the max-SSA bit) is rewritten to use an explicit stack rather than recursion so as not to overflow the stack in extreme cases when it does run.

Update to weval 0.2.12.

---

cmake/weval.cmake

This updates to refer to a new version of weval that has a CI fix so that Intel Macs get x86-64 binaries, not aarch64 binaries.

Update to weval 0.2.14.

---

builtins/web/streams/transform-stream.cpp

This fixes a panic Fastly was seeing when passing a request body to a response, where this slot was not a boolean causing a panic.

fix: panic on transform stream check

---

cmake/weval.cmake

This pulls in the latest changes, which mainly revolve around moving weval into place as a Bytecode Alliance Hosted Project, at its new repository at
[bytecodealliance/weval](https://github.com/bytecodealliance/weval).

Update to weval 0.3.2.

---

CMakeLists.txt

This ensures that `wasm-opt` does not strip the `"name"` section under `RelWithDebugInfo` builds (needed for ComponentizeJS).

fix: keep names section under RelWithDebInfo build

---

ADOPTERS.md
README.md

This updates the readme to note projects which are using StarlingMonkey (expected to be a list that can grow over time), which also seems useful for users to easily find where to use StarlingMonkey without having to build it themselves.

add links to consuming projects in readme

---

builtins/web/url.cpp
builtins/web/url.h
include/builtin.h

This is a first attempt to fix https://github.com/bytecodealliance/StarlingMonkey/issues/101 for further feedback.
In testing, I'm still not able to get the finalizer to run, as I believe we disable the GC during runtime still.
That said, supporting the GC running for long-running executions, and coding to avoid memory leaks still seem like important properties to retain for the runtime in general, even if not used.
@tschneidereit would very much value your feedback further here.

gc: add finalization for URL

---

CMakeLists.txt
builtins/web/fetch/headers.cpp
componentize.sh

This fixes the `componentize.sh` script to instead reference the locally installed toolchain, removing the need to have Wizer and wasm-tools in path.

fix: componentize script to use local bins

---

README.md

Uses the BA header style with the Zulip chat link.

add readme header with chat link

---

CMakeLists.txt
README.md
cmake/add_as_subproject.cmake
componentize.sh
include/config-parser.h
tests/tests.cmake
tests/wpt-harness/wpt.cmake

This changes the current `starling.wasm` build target to instead be called `starling-raw.wasm` to reflect that it's not yet a usable thing. Additionally, the current `runtime-eval` target is renamed to `starling` and produces a new `starling.wasm` file, which this time is a component that can be used to run dynamically loaded code.
I also updated the documentation accordingly.
And finally, I fixed a bug in `CMakeLists.txt` introduced in #151 that broke the `runtime-eval` build target. That's the entire reason I fell down this rabbit hole 😬

Make starling.wasm a usable component, and document it as such

---

host-apis/wasi-0.2.0/host_api.cpp
include/host_api.h

Besides some simplifications, this turns some checks that we know must pass into asserts instead.

Small improvements to the WASIp2 implementation of HttpOutgoingBody::write

---

cmake/openssl.cmake

Currently, when trying to build the project using the Ninja generator instead of Makefile, the build fails with the following error:
```
cmake -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -G Ninja
cmake --build cmake-build-debug
ninja: error: build.ninja:997: bad $-escape (literal $ must be written as $$)
```
This patch fixes the issue by checking for the actual make program name specifically for the Ninja generator.

Fix generation of Ninja files

---

runtime/script_loader.cpp

This fixes a bug where `filename` on CompileOptions was not being set for builtin modules in the script loader, which was fine on release builds but failing on debug builds.

fix: ensure filename is defined for builtins in debug builds

---

builtins/web/fetch/fetch_event.cpp
builtins/web/fetch/request-response.cpp
builtins/web/fetch/request-response.h
host-apis/wasi-0.2.0/host_api.cpp
include/host_api.h
tests/e2e/multi-stream-forwarding/expect_serve_body.txt
tests/e2e/multi-stream-forwarding/multi-stream-forwarding.js
tests/tests.cmake

This was pretty gnarly to work through, but I think came out reasonably clean. The two key pieces are:
- delaying the first read from an incoming stream that's been piped to a `TransformStream` until the latter is actually read from, and hence doesn't have backpressure applied anymore. This part guarantees that when the read would happen, we have the full pipeline in place and can hand things off to the host API instead of handling anything in the JS `fetch` API implementation.
- properly integrating these two pieces, and only closing the incoming body's `ReadableStream` once the host API reports that it's been dealt with to completion.
This PR additionally contains some fixes to how writes to bodies are handled, and some cleanup. These are both in separate patches which can be reviewed …

Fix bugs in handling multiple incoming bodies piped through a `TransFormStream` to an outgoing body

---

builtins/web/blob.cpp
builtins/web/blob.h
builtins/web/fetch/request-response.cpp
builtins/web/fetch/request-response.h
builtins/web/structured-clone.cpp
tests/wpt-harness/expectations/fetch/api/body/cloned-any.js.json
tests/wpt-harness/expectations/fetch/api/request/request-consume-empty.any.js.json
tests/wpt-harness/expectations/fetch/api/request/request-consume.any.js.json
tests/wpt-harness/expectations/fetch/api/request/request-disturbed.any.js.json
tests/wpt-harness/expectations/fetch/api/request/request-headers.any.js.json
tests/wpt-harness/expectations/fetch/api/request/request-init-contenttype.any.js.json
tests/wpt-harness/expectations/fetch/api/request/request-structure.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-consume-empty.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-error-from-stream.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-init-contenttype.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-stream-bad-chunk.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-1.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-2.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-3.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-4.any.js.json
tests/wpt-harness/expectations/html/webappapis/structured-clone/structured-clone.any.js.json

This patch adds `blob` API to `Request` and `Response` methods.
The patch also refactors the internal blob storage, changing it from `std::vector` to `mozilla::Vector`. This optimization allows the `Blob` to be created without copying data by transferring buffer ownership, as is the case for both `Response` and `Request` objects.
Closes: https://github.com/bytecodealliance/StarlingMonkey/issues/121

Add Request and Response blob methods

---

builtins/web/blob.cpp

There are two problems with this event loop interest management for the new blob StreamTask implementation:
1. I'm not seeing where non-cancelled stream tasks are getting their interest decremented
2. Event loop interest is purely about the request / response lifecycle requirements and not arbitrary immediate tracking
//cc @andreiltd

fix: remove invalid event loop interest bump

---

builtins/web/fetch/headers.cpp
builtins/web/fetch/headers.h

This adds support for a generation integer associated with headers mutations.
This allows for a quick check to determine if headers have been mutated since last seen by some code, useful for systems that need to store derived data based on headers (currently which we need at Fastly for cache state computations).

feat: support generation integer on headers objects

---

builtins/web/file.cpp
builtins/web/file.h
builtins/web/form-data.cpp
builtins/web/form-data.h
cmake/builtins.cmake
runtime/decode.h
runtime/encode.h
tests/wpt-harness/expectations/fetch/api/request/request-init-002.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-consume-stream.any.js.json
tests/wpt-harness/expectations/fetch/api/response/response-init-002.any.js.json
tests/wpt-harness/expectations/url/urlsearchparams-constructor.any.js.json
tests/wpt-harness/expectations/xhr/formdata/append.any.js.json
tests/wpt-harness/expectations/xhr/formdata/constructor.any.js.json
tests/wpt-harness/expectations/xhr/formdata/delete.any.js.json
tests/wpt-harness/expectations/xhr/formdata/foreach.any.js.json
tests/wpt-harness/expectations/xhr/formdata/get.any.js.json
tests/wpt-harness/expectations/xhr/formdata/has.any.js.json
tests/wpt-harness/expectations/xhr/formdata/iteration.any.js.json
tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
tests/wpt-harness/expectations/xhr/formdata/set.any.js.json
tests/wpt-harness/pre-harness.js
tests/wpt-harness/tests.json

This patch adds implementation of `FormaData`: https://xhr.spec.whatwg.org/#interface-formdata
I will add support for Request/Response `FormData` in a separate PR. 
Depends on https://github.com/bytecodealliance/StarlingMonkey/pull/181

Add implementation of `FormData` builtin

---

builtins/web/fetch/fetch-api.cpp
builtins/web/fetch/headers.cpp
builtins/web/fetch/request-response.cpp
tests/wpt-harness/expectations/fetch/api/basic/accept-header.any.js.json
tests/wpt-harness/expectations/fetch/api/basic/mode-same-origin.any.js.json
tests/wpt-harness/expectations/fetch/api/basic/request-forbidden-headers.any.js.json
tests/wpt-harness/expectations/fetch/api/basic/request-headers.any.js.json

This also fixes small bugs in how requests are created in `fetch` and what `Response#type` returns. Together, these fix a bunch of WPT tests, and this PR also fixes #145.

Filter out invalid header names when initializing Headers instances

---

builtins/web/blob.cpp
builtins/web/text-codec/text-decoder.cpp
builtins/web/text-codec/text-decoder.h

This patch fixes potential memory leaks by ensuring the `jsencoding::decoder_free()` is called for `jsencoding::decoder` instances.

Deallocate `jsencoding::Decoder` instances

---

builtins/web/crypto/crypto-algorithm.cpp
builtins/web/crypto/crypto.cpp
builtins/web/crypto/uuid.cpp
builtins/web/crypto/uuid.h
builtins/web/fetch/fetch-api.cpp
builtins/web/fetch/fetch-utils.cpp
builtins/web/fetch/fetch-utils.h
builtins/web/fetch/headers.cpp
builtins/web/fetch/request-response.cpp
builtins/web/fetch/request-response.h
builtins/web/url.cpp
builtins/web/url.h
cmake/builtins.cmake
cmake/compile-flags.cmake
host-apis/wasi-0.2.0/host_api.cpp
tests/integration/fetch/fetch.js
tests/wpt-harness/expectations/fetch/api/basic/request-upload.any.js.json
tests/wpt-harness/expectations/fetch/api/basic/scheme-blob.sub.any.js.json

This adds `URL.createObjectURL` and `URL.revokeObjectURL` static methods to URL as well as support for blob-scheme fetch:
- https://w3c.github.io/FileAPI/#dfn-createObjectURL
- https://fetch.spec.whatwg.org/#scheme-fetch
Some noteworthy changes include:
- move uuid generation function to a separate file so that it can be used outside `crypto` component,
- split main-fetch function into two `fetch-https` and `fetch-blob` functions called based on url scheme,
- implement Range content fetch for blobs,
- add integration tests for content range fetch.
Closes: https://github.com/bytecodealliance/StarlingMonkey/issues/182

Implement `URL.createObjectURL` and `URL.revokeObjectURL` methods

---

runtime/js.cpp

Resuming wizened snapshots means that clocks don't necessarily stay monotonic. This patch overrides `clock_gettime` to address that, by adding an offset determined at the end of wizening.
@andreiltd, this should fix the assert you encountered in #190, and hopefully allow us to do better on validating our GC rooting.

Ensure that monotonic clocks really are monotonic

---

README.md
justfile

This recipe will compile `starling.wasm`, componentize and serve the component with `wasmtime`.

Add `just` recipe for serving the js script

---

builtins/web/fetch/request-response.cpp

Removes what appears to be a debug print that slipped through.

stop printing request method to stderr when  is called

---

justfile
tests/wpt-harness/expectations/compression/compression-large-flush-output.any.js.json
tests/wpt-harness/expectations/compression/compression-with-detach.tentative.window.js.json
tests/wpt-harness/expectations/compression/decompression-with-detach.tentative.window.js.json
tests/wpt-harness/post-harness.js
tests/wpt-harness/wpt_builtins.cpp

WPT tests can load helper scripts using special comments at the top. These scripts need to be loaded as though using a `<script>` tag, which doesn't create a new lexical scope, and hence causes `let` and `const` bindings to be visible in the global scope.
Previously, to simulate this behavior using `eval`, the WPT harness replaced `let` and `const` with `var`. While this worked surprisingly well, it doesn't *always* work.
This commit instead introduces an `evalScript` function available to the harness, which evaluates in a way more closely matching that of script tags.

Fix loading of WPT META scripts

---

builtins/web/fetch/fetch_event.cpp
include/extension-api.h
runtime/engine.cpp

This logs all unhandled rejections to `stderr`, because they're pretty universally bugs to be addressed. Additionally, it logs a separate warning about rejection of promises passed to `FetchEvent#waitUntil`, for the same reason.

Log warnings for rejections left unhandled after FetchEvent handler completes

---

CMakeLists.txt
builtins/web/fetch/fetch_event.cpp
cmake/CPM.cmake
host-apis/wasi-0.2.0/host_api.cmake
host-apis/wasi-0.2.0/host_api.cpp
host-apis/wasi-0.2.3/host_api.cmake
host-apis/wasi-0.2.3/include/sockets.h
host-apis/wasi-0.2.3/sockets.cpp
include/config-parser.h
include/extension-api.h
runtime/debugger.cpp
runtime/debugger.h
runtime/engine.cpp
runtime/js.cpp

This PR introduces platform support for debugging JavaScript. "Platform support" here means that the PR doesn't contain an implementation of an actual debugger. Instead, it adds infrastructure to StarlingMonkey to initiate a debugging session over a TCP socket connection, and to load a JS implementation of an actual debugger via that connection.
The debugger itself works, but isn't quite ready for prime-time, so I'll open it as a draft PR, building on this one.
The debugger requires sort of a double opt-in: StarlingMonkey has to be started with the `-d/--enable-script-debugging` option set, and a port to connect to needs to be provided via the `DEBUGGER_PORT` env var. That ensures that StarlingMonkey will not try to read env vars at runtime without a prior opt-in, and hence will guarantee …

Add platform support for JS content debugging

---

componentize.sh.in
include/config-parser.h
include/extension-api.h
runtime/debugger.cpp
runtime/debugger.h
runtime/engine.cpp
runtime/script_loader.cpp
runtime/script_loader.h
tests/e2e/init-script/expect_serve_stdout.txt
tests/e2e/init-script/init-script.js
tests/e2e/init-script/init.js
tests/test.sh
tests/tests.cmake

This adds the ability to run  a script in a separate global before content gets run. This code has access to additional abilities, notably including the `defineBuiltinModule` function.
Building on this will allow us to change ComponentizeJS to support content using imports from `wasi:package-name` module names without rewriting the code first. That in turn will enable support for non-bundled content code.

Add support for running initialization scripts before content

---

ADOPTERS.md

We've been happily running StarlingMonkey in production for quite awhile, and didn't realize this page existed!

docs: Add Riza to the list of production adopters

---

builtins/web/fetch/headers.cpp

There is a bug in Fastly's header implementation where the invariant assertion in the `append_valid_normalized_header` of the header state was failing by calling Headers::lookup after doing the prepare entries for modification step.
Confirmed this resolves the issue in Fastly's test suite.

fix: prepare_for_entries_modification ordering

---

CMakeLists.txt
runtime/engine.cpp
tests/e2e/init-script/init.js

This fixes disabling the debugger API when not wanting to build the debugger.
I was hitting an issue where this was failing to find the `socket.h` in the Fastly build, and also we do want to keep the build minimal for now while we don't yet support this.

fix: debugger disabling

---

runtime/script_loader.cpp

Previously, these erors just logged an error to `stderr` and returned false, making it impossible to properly handle the errors.

Throw JS exceptions for errors in ScriptLoader

---

include/extension-api.h
runtime/engine.cpp

This way, builtins can add things to the global for the init script to use.
Also exposes the content global as `contentGlobal` in the init script global.

Expose the init script global to builtins

---

componentize.sh.in
include/config-parser.h
include/extension-api.h
runtime/engine.cpp
runtime/script_loader.cpp
runtime/script_loader.h
tests/e2e/runtime-err/expect_serve_stderr.txt
tests/e2e/syntax-err/expect_wizer_stderr.txt
tests/e2e/tla-err/expect_wizer_stderr.txt
tests/test.sh

This introduces the CLI option `--strip-path-prefix prefix` and strips the provided `prefix` from all paths as seen by content, in stack traces, and the debugger.
Previously, we unilaterally stripped the directory part of the top-level script's path instead. This new approach is better in two ways:
1. it works for files that are in ancestor or sibling directories to the top-level script
2. it enables using an ancestor directory as the root
The second of these advantages can be seen in the diffs to the test expectations files: the stacks for those are more informative, because they now include the directory of the actual test, since we're only stripping the `[StarlingMonkey root]/tests` part of the path.

Support stripping a prefix from all file paths

---

cmake/openssl.cmake

This updates OpenSSL to the latest version of the 3.0 release train, from the previous, very old, 3.0.7.
It also moves to using CPM to download and patch the OpenSSL source code, which speeds up building different configurations from the same source tree, and eliminates some issues where reconfiguring caused issues with applying the patches.

Update OpenSSL to version 3.0.16

---

include/config-parser.h

This patch fixes a bug in the CLI option parser that parses the argument to `--eval` twice, causing runtime initialization to interpret the argument as a script path, rather than an inline script. This is currently causing an example invocation in the README to fail:
```
wasmtime -S http starling.wasm -e "console.log('hello world')"
ReferenceError: Error loading module "console.log('hello world')"
(resolved path "console.log('hello world')"): No such file or directory
```

Fix parsing of the `--eval` CLI option

---

builtins/web/fetch/request-response.cpp

Something I've noticed is that headers for FormData are sometimes not initialized when we try to parse the request into formData. This ensures that the headers will be initialized if they haven't been already.

fix(formData): use headers instead of maybe_headers

---

CMakeLists.txt
host-apis/wasi-0.2.0/host_api.cpp
justfile
runtime/debugger.cpp
runtime/debugger.h
runtime/engine.cpp
tests/integration/fetch/fetch.js

This patch includes various fixes for how the debugger feature is enabled at compile time.
- Provide stub implementation of `content_debugger` for builds where `ENABLE_JS_DEBUGGER` is not defined
- Move `__wasilibc_initialize_environ` to debugger initialization to avoid implicit `wasi/environment` dependency.
There are currently 3 entry points where the content debugger can be initialized:
1. `http/handler` -- debugger initialization is now explicitly called in the StarlingMonkey fetch event: [here](https://github.com/bytecodealliance/StarlingMonkey/blob/main/builtins/web/fetch/fetch_event.cpp#L547)
2. `cli/run` -- debugger initialization should be called on engine initialization: [here](https://github.com/bytecodealliance/StarlingMonkey/blob/main/runtime/engine.cpp#L488)
3. …

fix(debugger): use ENABLE_JS_DEBUGGER instead of JS_DEBUGGER

---

.github/workflows/main.yml
CMakeLists.txt
componentize.sh.in
docs/src/getting-started/testing.md
include/config-parser.h
include/extension-api.h
justfile
runtime/engine.cpp
tests/wpt-harness/build-wpt-runtime.sh
tests/wpt-harness/run-wpt.mjs
tests/wpt-harness/wpt_builtins.cpp

Instead of requiring a CMake build config option to enable WPT support, with this change that's moved to the new `--wpt-mode` runtime flag.Instead of requiring a CMake build config option to enable WPT support, with this change that's moved to the new `--wpt-mode` runtime flag.
Also changes CI to only do one build of the runtime itself for all types of tests.

chore(build): Move WPT support build-time to runtime config
